### ISSUE TITLE
Under what license is this module published?

### ISSUE THREAD

**Issue by nhnFreespirit** [openresty/lua-ssl-nginx-module#14]
Unless I am missing something, I do not see any information about which license this module is published under.

A number of files simply state

/*
 * Copyright (C) CloudFlare Inc.
 */

Others have no license information at all.

Could you please clarify?

Thanks!

**Comment by agentzh** [comment]
@nhnFreespirit See

https://github.com/openresty/lua-ssl-nginx-module#copyright-and-license
