### ISSUE TITLE
why put do--end block in  global level in file 'lualib/ngx/ssl/session/ticket/key_rotation.lua'?

### ISSUE THREAD

**Issue by fankeke** [openresty/lua-ssl-nginx-module#4]
I test this excited feature, when I execute 'init_by_lua' phase , there always such errors presented : 
nginx: [error] init_by_lua_file error: ...y-memcached-shdict-master/lib/resty/memcached/shdict.lua:61: attempt to perform arithmetic on local 'memc_timeout' (a nil value)
stack traceback:
        ...y-memcached-shdict-master/lib/resty/memcached/shdict.lua:61: in function 'gen_memc_methods'
        ...nx-module/lualib/ngx/ssl/session/ticket/key_rotation.lua:92: in function 'func1_2'
        ...nx-module/lualib/ngx/ssl/session/ticket/key_rotation.lua:340: in function 'init'
        ...dev_online/ssl_session_ticket_rotation/rotation_init.lua:13: in main chunk

nginx: [error] init_by_lua_file error: ...nx-module/lualib/ngx/ssl/session/ticket/key_rotation.lua:216: attempt to perform arithmetic on local 'ticket_ttl' (a nil value)
stack traceback:
        ...nx-module/lualib/ngx/ssl/session/ticket/key_rotation.lua:216: in main chunk
        [C]: in function 'require'
        ...dev_online/ssl_session_ticket_rotation/rotation_init.lua:9: in main chunk

Such this error message.

I found this caused by  do-end block,  when execute init_phase , this block was also excuted,but these args has not been init by  _M.init() func.        
so I wrap  these do-end block  with local  functin() , and put these local  function in _M.init() 

then it works and no error message presented. 

So, Why put why put do--end block in  global level but not with local function? is there any consideration for this?? 

@agentzh

**Comment by xiewenhui** [comment]
@fankeke i have made a pull req to solve this issue ,  i think @agentzh will merge it soon 
https://github.com/openresty/lua-ssl-nginx-module/pull/3

**Comment by agentzh** [comment]
Merged. Please try the latest master out. Thanks!
