### ISSUE TITLE
feature request - add support for 80-byte tickets

### ISSUE THREAD

**Issue by craveica** [openresty/lua-ssl-nginx-module#6]
nginx 1.11.8 added support for 80-byte tickets. It would be nice if this module can handle 80-byte tickets.

**Comment by agentzh** [comment]
@craveica Mind to propose a pull request for that? Thanks!

**Comment by craveica** [comment]
Sorry, I don't have that kind of expertise.

**Comment by zhuizhuhaomeng** [comment]
Have merged this feature.

https://github.com/openresty/lua-ssl-nginx-module/pull/20
